export default {
  id: 'render_message_container',
  options: {
    duration: 3000,
    position: 'top_right',
  },
  styles: {
    message: {
      width: '250px',
      height: 'auto',
      border: '1px solid rgb(0 0 0 / 0.2)',
      borderRadius: '3px',
      boxShadow: '0 3px 10px rgb(0 0 0 / 0.2)',
      background: 'white',
      padding: '10px',
      margin: '5px 0',
      fontSize: '13px',
      boxSizing: 'border-box',
      opacity: 0,
      transform: 'translate(0, 0)',
      transition: 'transform ease-in-out 250ms, opacity ease-in-out 250ms',
      display: 'flex',
      alignItems: 'center',
    },
    button: {
      width: '18px',
      height: 'auto',
      background: 'transparent',
      border: 'none',
      cursor: 'pointer',
      padding: 0,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    },
    icon: {
      width: '18px',
      height: 'auto',
    },
    txt: {
      flex: 1,
      margin: '0 6px 0 0',
    },
    progress: {
      position: 'absolute',
      bottom: '1px',
      left: '1px',
      width: '0',
      height: '1px',
      background: 'rgb(0 0 0 / 0.2)',
    },
    centered: {
      width: '100%',
    },
  },
};
